# Generated by Django 3.2.2 on 2021-05-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('admissionClass', models.TextField(choices=[('Class I', 'Class I'), ('Class II', 'Class II'), ('Class III', 'Class III'), ('Class IV', 'Class IV'), ('Class V', 'Class V'), ('Class VI', 'Class VI'), ('Class VII', 'Class VII')], default='SODEXO', null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('dob', models.DateField(null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('father_name', models.CharField(max_length=100, null=True)),
                ('f_occupation', models.CharField(max_length=100, null=True)),
                ('f_qualification', models.CharField(max_length=100, null=True)),
                ('f_mobile', models.CharField(max_length=100, null=True)),
                ('mother_name', models.CharField(max_length=100, null=True)),
                ('m_occupation', models.CharField(max_length=100, null=True)),
                ('m_qualification', models.CharField(max_length=100, null=True)),
                ('alternateNo', models.CharField(max_length=100, null=True)),
                ('l_address', models.TextField(max_length=5000, null=True)),
                ('p_address', models.TextField(max_length=5000, null=True)),
                ('testDate', models.DateTimeField(auto_now_add=True)),
                ('testTime', models.DateTimeField(auto_now_add=True)),
                ('studentImage', models.ImageField(null=True, upload_to='static/images')),
                ('studentAadhar', models.ImageField(null=True, upload_to='static/images')),
                ('studentDOBCer', models.ImageField(null=True, upload_to='static/images')),
                ('studentTC', models.ImageField(null=True, upload_to='static/images')),
            ],
        ),
        migrations.DeleteModel(
            name='Receptions',
        ),
    ]
