# Generated by Django 3.2.2 on 2021-05-12 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210509_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reception',
            name='alternateNo',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='m_occupation',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='m_qualification',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='p_address',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='studentAadhar',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='studentDOBCer',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='studentImage',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='studentTC',
        ),
        migrations.AlterField(
            model_name='reception',
            name='admissionClass',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('admDate', models.DateTimeField(auto_now_add=True)),
                ('admNo', models.TextField(max_length=20, null=True)),
                ('admClass', models.TextField(max_length=100, null=True)),
                ('section', models.TextField(max_length=10, null=True)),
                ('rollNo', models.TextField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('busRoot', models.TextField(max_length=100, null=True)),
                ('stdType', models.BooleanField(default=True)),
                ('hostel', models.BooleanField(default=False)),
                ('hostelTyoe', models.BooleanField(default=False)),
                ('cast', models.TextField(choices=[('GENRAL', 'GENRAL'), ('OBC', 'OBC'), ('SC/ST', 'SC/ST'), ('Other', 'Other')], default='GENRAL')),
                ('religion', models.TextField(choices=[('HINDU', 'HINDU'), ('MUSLIM', 'MUSLIM'), ('Other', 'Other')], default='HINDU')),
                ('p_address', models.TextField(max_length=5000, null=True)),
                ('studentImage', models.ImageField(null=True, upload_to='static/images')),
                ('studentAadhar', models.ImageField(null=True, upload_to='static/images')),
                ('studentDOBCer', models.ImageField(null=True, upload_to='static/images')),
                ('studentTC', models.ImageField(null=True, upload_to='static/images')),
                ('l_address', models.TextField(max_length=5000, null=True)),
                ('testDate', models.DateTimeField(auto_now_add=True)),
                ('testTime', models.DateTimeField(auto_now_add=True)),
                ('reception', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='polls.reception')),
            ],
        ),
    ]
