# Generated by Django 3.2.2 on 2021-05-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210512_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='l_address',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='testDate',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='testTime',
        ),
        migrations.AddField(
            model_name='admission',
            name='alternateNo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='m_occupation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='m_qualification',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
