# Generated by Django 3.2.2 on 2021-05-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210512_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='admClass',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='admNo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='rollNo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='section',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
