# Generated by Django 3.2.2 on 2021-05-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210512_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='admissionClass',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='f_mobile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='f_occupation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='f_qualification',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='father_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='l_address',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='mother_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
