# Generated by Django 3.2.2 on 2021-05-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210512_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('c_name', models.CharField(max_length=20, null=True)),
                ('c_fee', models.CharField(max_length=20, null=True)),
                ('f_inst', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
