# Generated by Django 3.2.2 on 2021-05-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_addclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('section', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
