# Generated by Django 3.2.2 on 2021-05-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_addsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bus_name', models.CharField(max_length=50, null=True)),
                ('root_name', models.CharField(max_length=50, null=True)),
                ('root_fee', models.CharField(max_length=20, null=True)),
                ('root_inst', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
