# Generated by Django 3.2.2 on 2021-05-18 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_busroot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraFeeStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fee_name', models.CharField(max_length=50, null=True)),
                ('extra_fee', models.CharField(max_length=20, null=True)),
                ('admission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extraFeeStructure', to='polls.admission')),
            ],
        ),
    ]
