# Generated by Django 3.2.2 on 2021-05-19 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_extrafeestructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='addclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='polls.addclass'),
        ),
        migrations.AddField(
            model_name='reception',
            name='addclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reception', to='polls.addclass'),
        ),
    ]
