# Generated by Django 3.2.2 on 2021-05-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20210519_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='stdType',
            field=models.TextField(choices=[('ALL STUDENT', 'ALL STUDENT'), ('NEW', 'NEW'), ('OLD', 'OLD')], default='NEW'),
        ),
    ]
