# Generated by Django 3.2.2 on 2021-05-20 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_admission_stdtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='stdType',
        ),
        migrations.RemoveField(
            model_name='extrafeestructure',
            name='admission',
        ),
        migrations.AddField(
            model_name='extrafeestructure',
            name='reception',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extraFeeStructure', to='polls.reception'),
        ),
        migrations.AddField(
            model_name='extrafeestructure',
            name='stdType',
            field=models.TextField(choices=[('ALL STUDENT', 'ALL STUDENT'), ('NEW', 'NEW'), ('OLD', 'OLD')], default='NEW'),
        ),
    ]
