# Generated by Django 3.2.2 on 2021-05-20 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20210520_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrafeestructure',
            name='addclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extraFeeStructure', to='polls.addclass'),
        ),
    ]
