# Generated by Django 3.2.2 on 2021-05-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_extrafeestructure_addclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrafeestructure',
            name='month',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
