# Generated by Django 3.2.2 on 2021-05-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_extrafeestructure_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='busRoot',
        ),
    ]
