# Generated by Django 3.2.2 on 2021-05-20 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_remove_admission_busroot'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='busRoot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='polls.busroot'),
        ),
    ]
