# Generated by Django 3.2.2 on 2021-05-21 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_admission_busroot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddHostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('h_name', models.CharField(max_length=20, null=True)),
                ('h_fee', models.CharField(max_length=20, null=True)),
                ('h_inst', models.CharField(max_length=20, null=True)),
                ('h_instruction', models.CharField(max_length=1000, null=True)),
                ('addclass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addHostel', to='polls.addclass')),
                ('admission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addHostel', to='polls.admission')),
                ('reception', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addHostel', to='polls.reception')),
            ],
        ),
    ]
