# Generated by Django 3.2.2 on 2021-05-23 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_addhostel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mode_name', models.CharField(max_length=20, null=True)),
                ('mode_type', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('income_details', models.TextField(max_length=2000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.CharField(max_length=200, null=True)),
                ('goods', models.CharField(max_length=2000, null=True)),
                ('cheque_no', models.CharField(max_length=200, null=True)),
                ('bank_name', models.CharField(max_length=200, null=True)),
                ('descrption', models.TextField(max_length=2000, null=True)),
                ('income_type', models.CharField(max_length=20, null=True)),
                ('mode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income', to='polls.mode')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expense_details', models.TextField(max_length=2000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.CharField(max_length=200, null=True)),
                ('expense_type', models.CharField(max_length=20, null=True)),
                ('cheque_no', models.CharField(max_length=200, null=True)),
                ('bank_name', models.CharField(max_length=200, null=True)),
                ('mode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='polls.mode')),
            ],
        ),
    ]
