# Generated by Django 3.2.2 on 2021-05-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_alter_reception_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
