# Generated by Django 3.2.2 on 2021-05-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_alter_reception_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='admDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
