# Generated by Django 3.2.2 on 2021-05-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_alter_admission_admdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='admDate',
            field=models.DateField(null=True),
        ),
    ]
