# Generated by Django 3.2.2 on 2021-05-28 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_alter_admission_admdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admission',
            new_name='Admissions',
        ),
    ]
