# Generated by Django 3.2.2 on 2021-05-28 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_auto_20210528_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('admissionClass', models.TextField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('dob', models.DateField(null=True)),
                ('father_name', models.CharField(max_length=100, null=True)),
                ('f_occupation', models.CharField(max_length=100, null=True)),
                ('f_qualification', models.CharField(max_length=100, null=True)),
                ('f_mobile', models.CharField(max_length=100, null=True)),
                ('mother_name', models.CharField(max_length=100, null=True)),
                ('l_address', models.TextField(max_length=5000, null=True)),
                ('admdate', models.DateField(auto_now_add=True)),
                ('admNo', models.CharField(max_length=20, null=True)),
                ('admClass', models.CharField(max_length=100, null=True)),
                ('section', models.CharField(max_length=10, null=True)),
                ('rollNo', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('hostel', models.BooleanField(default=False)),
                ('hostelTyoe', models.BooleanField(default=False)),
                ('cast', models.TextField(choices=[('GENRAL', 'GENRAL'), ('OBC', 'OBC'), ('SC/ST', 'SC/ST'), ('Other', 'Other')], default='GENRAL')),
                ('religion', models.TextField(choices=[('HINDU', 'HINDU'), ('MUSLIM', 'MUSLIM'), ('Other', 'Other')], default='HINDU')),
                ('p_address', models.TextField(max_length=5000, null=True)),
                ('m_occupation', models.CharField(max_length=100, null=True)),
                ('m_qualification', models.CharField(max_length=100, null=True)),
                ('alternateNo', models.CharField(max_length=100, null=True)),
                ('studentImage', models.ImageField(null=True, upload_to='static/images')),
                ('studentAadhar', models.ImageField(null=True, upload_to='static/images')),
                ('studentDOBCer', models.ImageField(null=True, upload_to='static/images')),
                ('studentTC', models.ImageField(null=True, upload_to='static/images')),
                ('addclass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='polls.addclass')),
                ('busRoot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='polls.busroot')),
                ('reception', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='polls.reception')),
            ],
        ),
        migrations.AlterField(
            model_name='addhostel',
            name='admission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addHostel', to='polls.admissions'),
        ),
        migrations.DeleteModel(
            name='Admission',
        ),
    ]
