# Generated by Django 3.2.2 on 2021-05-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_auto_20210528_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissions',
            name='admdate',
        ),
        migrations.AddField(
            model_name='admissions',
            name='admDate',
            field=models.DateField(null=True),
        ),
    ]
