# Generated by Django 3.2.2 on 2021-05-28 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0032_auto_20210528_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissions',
            name='addclass',
        ),
    ]
