# Generated by Django 3.2.2 on 2021-05-28 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_remove_admissions_addclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissions',
            name='addclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='polls.addclass'),
        ),
    ]
