# Generated by Django 3.2.2 on 2021-05-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0034_admissions_addclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissions',
            name='admDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
