# Generated by Django 3.2.2 on 2021-05-28 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0035_alter_admissions_admdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissions',
            name='addclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='polls.addclass'),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='busRoot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='polls.busroot'),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='reception',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='polls.reception'),
        ),
    ]
