# Generated by Django 3.2.2 on 2021-05-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0036_auto_20210528_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addhostel',
            name='admission',
        ),
        migrations.DeleteModel(
            name='Admissions',
        ),
    ]
