# Generated by Django 3.2.2 on 2021-05-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0038_admissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
