# Generated by Django 3.2.2 on 2021-05-29 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0039_auto_20210529_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExepenseMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('mode_name', models.CharField(max_length=20, null=True)),
                ('mode_type', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('mode_name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='expense',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='income',
            name='mode',
        ),
        migrations.AddField(
            model_name='addhostel',
            name='admission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addHostel', to='polls.admissions'),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reception',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Mode',
        ),
        migrations.AddField(
            model_name='expense',
            name='expenseMode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='polls.exepensemode'),
        ),
        migrations.AddField(
            model_name='income',
            name='incomeMode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income', to='polls.incomemode'),
        ),
    ]
