# Generated by Django 3.2.2 on 2021-05-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0040_auto_20210529_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissions',
            name='created',
            field=models.DateField(null=True),
        ),
    ]
