# Generated by Django 3.2.2 on 2021-05-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0041_alter_admissions_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissions',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reception',
            name='created',
            field=models.DateField(null=True),
        ),
    ]
