# Generated by Django 3.2.2 on 2021-06-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0043_rename_incomemode_income_incomemode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('bank_name', models.CharField(max_length=50, null=True)),
                ('acc_no', models.CharField(max_length=30, null=True)),
                ('ifsc', models.CharField(max_length=30, null=True)),
                ('address', models.TextField(max_length=2000, null=True)),
            ],
        ),
    ]
