# Generated by Django 3.2.2 on 2021-06-02 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0044_addbank'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankWithdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('with_details', models.TextField(max_length=2000, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.CharField(max_length=200, null=True)),
                ('income_type', models.CharField(max_length=20, null=True)),
                ('cheque_no', models.CharField(max_length=200, null=True)),
                ('bank_name', models.CharField(max_length=200, null=True)),
                ('depo_name', models.CharField(max_length=200, null=True)),
                ('addbank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bankwithdraw', to='polls.addbank')),
            ],
        ),
        migrations.CreateModel(
            name='BankDeposite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('depo_details', models.TextField(max_length=2000, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.CharField(max_length=200, null=True)),
                ('income_type', models.CharField(max_length=20, null=True)),
                ('cheque_no', models.CharField(max_length=200, null=True)),
                ('bank_name', models.CharField(max_length=200, null=True)),
                ('depo_name', models.CharField(max_length=200, null=True)),
                ('addbank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bankdeposite', to='polls.addbank')),
            ],
        ),
    ]
