# Generated by Django 3.2.2 on 2021-06-03 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0045_bankdeposite_bankwithdraw'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('department_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('j_date', models.DateField(auto_now_add=True)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('basicSal', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('subject', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('dob', models.DateField(null=True)),
                ('father_name', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=100, null=True)),
                ('mother_name', models.CharField(max_length=100, null=True)),
                ('husband_name', models.CharField(max_length=100, null=True)),
                ('staff_qualification', models.CharField(max_length=100, null=True)),
                ('bankSal', models.CharField(max_length=100, null=True)),
                ('l_address', models.TextField(max_length=5000, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('p_address', models.TextField(max_length=5000, null=True)),
                ('alternateNo', models.CharField(max_length=100, null=True)),
                ('staffImage', models.ImageField(null=True, upload_to='static/images')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addstaff', to='polls.adddepartment')),
            ],
        ),
    ]
