# Generated by Django 3.2.2 on 2021-06-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0046_adddepartment_addstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddExamTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('term_name', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
