# Generated by Django 3.2.2 on 2021-06-03 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0047_addexamterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddExamSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('subject1', models.CharField(max_length=50, null=True)),
                ('marks1', models.CharField(max_length=50, null=True)),
                ('subject2', models.CharField(max_length=50, null=True)),
                ('marks2', models.CharField(max_length=50, null=True)),
                ('subject3', models.CharField(max_length=50, null=True)),
                ('marks3', models.CharField(max_length=50, null=True)),
                ('subject4', models.CharField(max_length=50, null=True)),
                ('marks4', models.CharField(max_length=50, null=True)),
                ('subject5', models.CharField(max_length=50, null=True)),
                ('marks5', models.CharField(max_length=50, null=True)),
                ('subject6', models.CharField(max_length=50, null=True)),
                ('marks6', models.CharField(max_length=50, null=True)),
                ('subject7', models.CharField(max_length=50, null=True)),
                ('marks7', models.CharField(max_length=50, null=True)),
                ('subject8', models.CharField(max_length=50, null=True)),
                ('marks8', models.CharField(max_length=50, null=True)),
                ('subject9', models.CharField(max_length=50, null=True)),
                ('marks9', models.CharField(max_length=50, null=True)),
                ('subject10', models.CharField(max_length=50, null=True)),
                ('marks10', models.CharField(max_length=50, null=True)),
                ('subject11', models.CharField(max_length=50, null=True)),
                ('marks11', models.CharField(max_length=50, null=True)),
                ('subject12', models.CharField(max_length=50, null=True)),
                ('marks12', models.CharField(max_length=50, null=True)),
                ('subject13', models.CharField(max_length=50, null=True)),
                ('marks13', models.CharField(max_length=50, null=True)),
                ('subject14', models.CharField(max_length=50, null=True)),
                ('marks14', models.CharField(max_length=50, null=True)),
                ('subject15', models.CharField(max_length=50, null=True)),
                ('marks15', models.CharField(max_length=50, null=True)),
                ('addclass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addexamsubject', to='polls.addclass')),
                ('examterm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addexamsubject', to='polls.addexamterm')),
            ],
        ),
    ]
