# Generated by Django 3.2.2 on 2021-06-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0048_addexamsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='addclass',
            name='marks1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addclass',
            name='marks10',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addclass',
            name='marks11',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addclass',
            name='marks12',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addclass',
            name='marks13',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addclass',
            name='marks14',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addclass',
            name='marks15',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addclass',
            name='marks2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addclass',
            name='marks3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addclass',
            name='marks4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addclass',
            name='marks5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addclass',
            name='marks6',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addclass',
            name='marks7',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addclass',
            name='marks8',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addclass',
            name='marks9',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addclass',
            name='subject1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addclass',
            name='subject10',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addclass',
            name='subject11',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addclass',
            name='subject12',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addclass',
            name='subject13',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addclass',
            name='subject14',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addclass',
            name='subject15',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addclass',
            name='subject2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addclass',
            name='subject3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addclass',
            name='subject4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addclass',
            name='subject5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addclass',
            name='subject6',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addclass',
            name='subject7',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addclass',
            name='subject8',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addclass',
            name='subject9',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
