# Generated by Django 3.2.2 on 2021-06-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0050_auto_20210604_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addhostel',
            name='addclass',
        ),
        migrations.RemoveField(
            model_name='addhostel',
            name='reception',
        ),
    ]
