# Generated by Django 3.2.2 on 2021-06-04 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0051_auto_20210604_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissions',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='admissions',
            name='hostelTyoe',
        ),
    ]
