# Generated by Django 3.2.2 on 2021-06-05 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0053_classfeediscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='classfeediscount',
            name='addadmission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classFeeDiscount', to='polls.admissions'),
        ),
    ]
