# Generated by Django 3.2.2 on 2021-06-09 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0054_classfeediscount_addadmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusFeeDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('amount', models.CharField(max_length=500, null=True)),
                ('month', models.CharField(max_length=50, null=True)),
                ('t_amount', models.CharField(max_length=50, null=True)),
                ('addadmission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='busFeeDiscount', to='polls.admissions')),
                ('addclass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='busFeeDiscount', to='polls.addclass')),
                ('addsection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='busFeeDiscount', to='polls.addsection')),
            ],
        ),
    ]
