# Generated by Django 3.2.2 on 2021-06-15 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0056_hostelfeediscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busfeediscount',
            name='addadmission',
        ),
        migrations.RemoveField(
            model_name='classfeediscount',
            name='addadmission',
        ),
        migrations.RemoveField(
            model_name='hostelfeediscount',
            name='addadmission',
        ),
        migrations.AddField(
            model_name='admissions',
            name='busfeedicount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='polls.busfeediscount'),
        ),
        migrations.AddField(
            model_name='admissions',
            name='classfeediscount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='polls.classfeediscount'),
        ),
        migrations.AddField(
            model_name='admissions',
            name='hostelfeedisount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='polls.hostelfeediscount'),
        ),
    ]
