# Generated by Django 3.2.2 on 2021-06-15 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0057_auto_20210615_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissions',
            name='busfeedicount',
        ),
        migrations.RemoveField(
            model_name='admissions',
            name='classfeediscount',
        ),
        migrations.RemoveField(
            model_name='admissions',
            name='hostelfeedisount',
        ),
        migrations.AddField(
            model_name='busfeediscount',
            name='addadmission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='busFeeDiscount', to='polls.admissions'),
        ),
        migrations.AddField(
            model_name='classfeediscount',
            name='addadmission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classFeeDiscount', to='polls.admissions'),
        ),
        migrations.AddField(
            model_name='hostelfeediscount',
            name='addadmission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostelFeeDiscount', to='polls.admissions'),
        ),
    ]
